apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/jenkinsxworkshop/gomar4serverless:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/jenkinsxworkshop/gomar4serverless:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: gomar4serverless
        chartPath: charts/gomar4serverless
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/jenkinsxworkshop/gomar4serverless'
          image.tag: '{{.DIGEST_HEX}}'
